volumes:
  mongodb-data:

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}



