volumes:
  mongodb-data:

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - './frontend:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dev
  backend:
    build:
      context: ./backend
    env_file:
      - .env  
    expose:
      - "8000"
    depends_on:
      - mongo
    networks:
      - dev
  mongo:
    image: mongo
    restart: always
    networks:
      - dev
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
